#!/usr/bin/env bash
# Session checkpoint hook — runs on Stop event.
# Captures git state + working tree snapshot to memory so the next session has continuity.
#
# Memory location is per-project (Claude Code convention):
#   ~/.claude/projects/<encoded-project-path>/memory/_session_checkpoint.md
#
# Receives JSON on stdin (session_id, transcript_path, cwd, hook_event_name, stop_reason).
# We don't currently parse it, but read & discard so the producer doesn't block.

set -uo pipefail

# Drain stdin (ignore content)
cat > /dev/null 2>&1 || true

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
cd "$PROJECT_DIR" || exit 0

# Memory dir is named after the project path with slashes replaced by dashes,
# prefixed with a dash. This matches Claude Code's encoding.
ENCODED_PATH="-$(echo "$PROJECT_DIR" | sed 's|/|-|g' | sed 's|^-||')"
MEMORY_DIR="$HOME/.claude/projects/$ENCODED_PATH/memory"
CHECKPOINT="$MEMORY_DIR/_session_checkpoint.md"

# Bail quietly if the memory dir doesn't exist (e.g. fresh project, no memory yet)
[ -d "$MEMORY_DIR" ] || exit 0

BRANCH=$(git branch --show-current 2>/dev/null || echo "(unknown)")
LAST_COMMIT=$(git log -1 --oneline 2>/dev/null || echo "(no commits)")
RECENT=$(git log --oneline -5 2>/dev/null || echo "")
STATUS=$(git status --porcelain 2>/dev/null || echo "")
TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M UTC")

# Detect open PRs from the current branch
PR_INFO=""
if command -v gh >/dev/null 2>&1 && [ "$BRANCH" != "(unknown)" ] && [ "$BRANCH" != "main" ]; then
  PR_INFO=$(gh pr list --head "$BRANCH" --json number,title,state,url 2>/dev/null || echo "")
fi

{
  echo "---"
  echo "name: latest session checkpoint"
  echo "description: Auto-generated git+task snapshot at session end; provides continuity for the next session"
  echo "type: project"
  echo "---"
  echo ""
  echo "**Session ended:** $TIMESTAMP"
  echo ""
  echo "## Branch"
  echo "- Current: \`$BRANCH\`"
  echo "- Last commit: $LAST_COMMIT"
  echo ""
  echo "## Recent commits (last 5)"
  echo '```'
  echo "$RECENT"
  echo '```'
  echo ""
  echo "## Working tree at session end"
  echo '```'
  if [ -z "$STATUS" ]; then
    echo "(clean)"
  else
    echo "$STATUS"
  fi
  echo '```'
  if [ -n "$PR_INFO" ] && [ "$PR_INFO" != "[]" ]; then
    echo ""
    echo "## Open PR(s) from this branch"
    echo '```json'
    echo "$PR_INFO"
    echo '```'
  fi
  echo ""
  echo "> Auto-generated by \`.claude/hooks/session-checkpoint.sh\`."
  echo "> When picking up work, verify this is still current via \`git status\` and \`git log\` before acting."
} > "$CHECKPOINT" 2>/dev/null || true

exit 0
